---
abstract: 'http://handlebarsjs.com/ for Text::Xslate'
author:
  - 'Jesse Luehrs <doy at cpan dot org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Sub::Exporter: 0
  Test::Builder: 0
  Test::Fatal: 0
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Handlebars
no_index:
  package:
    - Text::Handlebars::Compiler
    - Text::Handlebars::Symbol
    - Text::Xslate::Syntax::Handlebars
requires:
  Any::Moose: 0
  Carp: 0
  Scalar::Util: 0
  Text::Xslate: 1.6000
  Text::Xslate::Compiler: 0
  Text::Xslate::Parser: 0
  Text::Xslate::Symbol: 0
  Text::Xslate::Util: 0
  Try::Tiny: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Handlebars
  homepage: http://metacpan.org/release/Text-Handlebars
  repository: git://github.com/doy/text-handlebars.git
version: 0.02
x_Dist_Zilla:
  perl:
    version: 5.016002
  plugins:
    -
      class: Dist::Zilla::Plugin::FileFinder::Filter
      name: WeaverFiles
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreDoneTesting'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Filter/RunExtraTests'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Filter/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Filter/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Filter/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Filter/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Metadata
      name: '@Filter/Metadata'
      version: 3.03
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@Filter/MetaResources'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git::Check'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git::Commit'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Git::Tag'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300028
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300028
x_authority: cpan:DOY
